### PR TITLE
decreased debounce time from 300 to 50

### PR DESCRIPTION
**Pull request by illmat**
The debounce time has to be lowered. It took us a while to figure out why some fields are not being updated.

### CODE REVIEW

**Comment by quietcreep** [comment]
If ```_.debounce``` worked the way it should, it wouldn't keep fields from updating due to a longer wait time. Is something else going on here? Maybe a bug with debounce? Have you tested the change?

**Comment by illmat** [comment]
Yes, I've tested the change, seems to work fine now.
To reproduce it, make a model with 3 or 4 fields and fill them fast via <tab> <some-char>, <tab> <some-char>,...
That way some events don't get triggered.
It happend to me even when I was using the mouse.
Also you could set the debounce time to something like 3000 for testing purposes.

**Comment by quietcreep** [comment]
I'll trust you on it. And I don't think it's going to be expensive enough to make a difference anyways.

**Comment by quietcreep** [comment]
Also, thanks!

**Pull request merged**
